/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                primary: "#006767",
                "surface-container-high": "#e8e8ea",
                "surface-container-low": "#f3f3f6",
                tertiary: "#006a3b",
                "on-primary": "#ffffff",
                "on-background": "#1a1c1e",
                "on-surface-variant": "#3d4949",
                "surface-container": "#eeeef0",
                secondary: "#006a65",
                "inverse-surface": "#2f3133",
                outline: "#6d7979",
                "surface-tint": "#006a6a",
                "outline-variant": "#bcc9c8",
                surface: "#f9f9fc",
                "surface-variant": "#e2e2e5",
                "primary-container": "#008282",
                background: "#f9f9fc",
                "on-surface": "#1a1c1e",
                "surface-bright": "#f9f9fc",
                "surface-container-lowest": "#ffffff",
                "surface-dim": "#dadadc",
                "surface-container-highest": "#e2e2e5",
                "on-error-container": "#93000a",
                error: "#ba1a1a",
                "on-tertiary-fixed-variant": "#00522d",
                "tertiary-fixed-dim": "#7ed99e",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#00504c",
                "primary-fixed-dim": "#6fd7d6",
                "secondary-fixed-dim": "#59dad1",
                "tertiary-container": "#268451",
                "on-primary-fixed": "#002020",
                "tertiary-fixed": "#9af6b8",
                "inverse-on-surface": "#f0f0f3",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed": "#00210f",
                "on-tertiary-container": "#f6fff4",
                "primary-fixed": "#8cf3f3",
                "inverse-primary": "#6fd7d6",
                "secondary-container": "#76f3ea",
                "error-container": "#ffdad6",
                "on-secondary-fixed": "#00201e",
                "on-error": "#ffffff",
                "secondary-fixed": "#79f6ed",
                "on-primary-fixed-variant": "#004f4f",
                "on-secondary-container": "#006f69",
                "on-primary-container": "#f3fffe",
            },
            spacing: {
                md: "24px",
                gutter: "16px",
                base: "8px",
                sm: "12px",
                xs: "4px",
                lg: "40px",
                xl: "64px",
                margin: "20px",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            fontFamily: {
                "headline-lg": ["Manrope", "sans-serif"],
                "label-sm": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "headline-md": ["Manrope", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "display-lg": ["Manrope", "sans-serif"],
                "label-lg": ["Inter", "sans-serif"],
            },
        },
    },
    plugins: [],
};
